// rustrender — Web Worker rendering pipeline (route C).
//
// Receives { id, markdown, options } jobs, renders via the rustrender-wasm
// module, posts back { id, ok, payload|error, renderMs }.
// wasm-bindgen output is expected at ./bindings/rustrender_wasm.js
// (generated by: wasm-bindgen --target web --out-dir bindings/ ...).

let wasmInit = null;

async function ensureWasm() {
    if (!wasmInit) {
        const mod = await import('./bindings/rustrender_wasm.js');
        wasmInit = mod.default();          // returns init promise factory
        await wasmInit;
        self.__rustrender = await import('./bindings/rustrender_wasm.js');
    }
    return self.__rustrender;
}

self.onmessage = async (ev) => {
    const { id, markdown, options } = ev.data || {};
    const t0 = performance.now();
    try {
        const mod = await ensureWasm();
        const json = mod.render_markdown_json(markdown, JSON.stringify(options || {}));
        const out = JSON.parse(json);
        self.postMessage({
            id,
            ok: true,
            payload: out,
            renderMs: performance.now() - t0,
        });
    } catch (e) {
        self.postMessage({
            id,
            ok: false,
            error: String(e && e.message ? e.message : e),
            renderMs: performance.now() - t0,
        });
    }
};
